table dim_education
	lineageTag: 66e0a1ca-864b-4735-b4f0-7f1315d89c6c

	column Education_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: cacb2e81-9a13-46f3-958f-dac121e54b26
		summarizeBy: none
		sourceColumn: Education_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Education Level'
		dataType: string
		lineageTag: 971309e4-2373-4815-8c80-ab3a597bed20
		summarizeBy: none
		sourceColumn: Education Level

		annotation SummarizationSetBy = Automatic

	partition dim_education = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\mjt70\OneDrive\Desktop\Repo\pbi-ai-jobs-project\data\processed\dim_education.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Education_Level", "Education Level"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

