table dim_job
	lineageTag: 80331446-d1b5-49b9-8bb5-2f7bbf0e42d8

	column Job_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1df19a67-3130-41d5-9da2-114b79678834
		summarizeBy: none
		sourceColumn: Job_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Job Title'
		dataType: string
		lineageTag: 818f0658-4ded-45a7-8a3c-940500ad56ed
		summarizeBy: none
		sourceColumn: Job Title

		annotation SummarizationSetBy = Automatic

	column 'Automation Level'
		dataType: string
		lineageTag: e6d3dfb8-62ba-4244-9645-e4753a68bd6d
		summarizeBy: none
		sourceColumn: Automation Level

		annotation SummarizationSetBy = Automatic

	column 'AI Tool Usage'
		dataType: string
		lineageTag: 4e255d4c-c115-4434-9812-1012e0e0e581
		summarizeBy: none
		sourceColumn: AI Tool Usage

		annotation SummarizationSetBy = Automatic

	column 'Upskilling Needed'
		dataType: string
		lineageTag: 59f791ff-dfdb-4b82-ae66-c86024522259
		summarizeBy: none
		sourceColumn: Upskilling Needed

		annotation SummarizationSetBy = Automatic

	partition dim_job = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\mjt70\OneDrive\Desktop\Repo\pbi-ai-jobs-project\data\processed\dim_job.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"AI_Tool_Usage", "AI Tool Usage"}, {"Automation_Level", "Automation Level"}, {"Job_Title", "Job Title"}, {"Upskilling_Needed", "Upskilling Needed"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

